name: 🐛 Bug Report
description: File a bug report to help us improve
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Affected Version
      description: What version of gt are you using?
      placeholder: "v1.5.1"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce the problem?
    validations:
      required: false
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
    validations:
      required: true
