#!/usr/bin/env bash

# gget remote add ...
# gget remote remove ...
# gget remote list ...
# take at look at gget-remote.doc.sh for more information

# gget pull ...
# take at look at gget-pull.doc.sh for more information

# gget re-pull ...
# take at look at gget-re-pull.doc.sh for more information

# gget reset ...
# take at look at gget-reset.doc.sh for more information

# gget update ...
# take at look at gget-update.doc.sh for more information

# gget self-update
# take at look at gget-self-update.doc.sh for more information
