#!/usr/bin/env bash

# gt remote add ...
# gt remote remove ...
# gt remote list ...
# take at look at gt-remote.doc.sh for more information

# gt pull ...
# take at look at gt-pull.doc.sh for more information

# gt re-pull ...
# take at look at gt-re-pull.doc.sh for more information

# gt reset ...
# take at look at gt-reset.doc.sh for more information

# gt update ...
# take at look at gt-update.doc.sh for more information

# gt self-update
# take at look at gt-self-update.doc.sh for more information
